# Generated by Django 3.0.2 on 2020-06-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.IntegerField(),
        ),
    ]
